### PR TITLE
Add support for the --team flag

### PR DESCRIPTION
**Pull request by dmcinnes**
Depends on https://github.com/heroku/cli-engine-command/pull/28
Keeps `flags.org` for backwards-compatibility.

This should wait to go out with the Enterprise Teams release.

### CODE REVIEW

**Comment by dickeyxxx** [comment]
why do we need to add this? is it because it needs to be set via an env var?

**Comment by jdx** [comment]
leaving this open for now because it's an easier solution, but I'd prefer us to do #126, which isn't much work, but v6 would need to be fully released first.

**Comment by garyposter** [comment]
@dmcinnes you told Jeff that this is not a pressing request--even a couple of months would fine. Therefore we intend to do it with v6. @RasPhilCo will reach out to you soon to figure out some details on how this should work.

**Comment by garyposter** [comment]
Trello for Philipe's work: https://trello.com/c/MlkMM4xV/815-add-a-new-team-flag-and-deprecate-others-as-appropriate

**Comment by jdx** [comment]
looking at this again I think it's good but we should put the team flag into a new heroku-specific repo to reduce the amount of heroku-specific code in cli-engine-command

**Comment by jdx** [comment]
closed in favor of #140

**Pull request closed without merging**
